# Generated by Django 5.2 on 2025-04-08 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bunker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Doenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("origem", models.TextField(blank=True)),
                ("contagiosa", models.BooleanField(default=False)),
                (
                    "forma_contagio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parte_afetada",
                    models.CharField(
                        choices=[
                            ("CAB", "Cabeça"),
                            ("COR", "Coração"),
                            ("PUL", "Pulmões"),
                            ("EST", "Estômago"),
                            ("PEL", "Pele"),
                            ("OSS", "Ossos"),
                            ("MEN", "Mente"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("F", "Física"), ("M", "Mental"), ("B", "Ambas")],
                        max_length=1,
                    ),
                ),
                (
                    "tratamento",
                    models.TextField(
                        blank=True, help_text="Protocolo de tratamento recomendado"
                    ),
                ),
                (
                    "reacoes_esperadas",
                    models.TextField(
                        blank=True, help_text="Reações esperadas ao tratamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doença",
                "verbose_name_plural": "Doenças",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Sintoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("F", "Físico"), ("M", "Mental")], max_length=1
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                (
                    "tipo_sanguineo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ESTAVEL", "Estável"),
                            ("TRATAMENTO", "Em Tratamento"),
                            ("CRONICO", "Tratamento Crônico"),
                            ("OBITO", "Óbito"),
                        ],
                        default="ESTAVEL",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "bunker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes",
                        to="core.bunker",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pacientes",
                "ordering": ["bunker__nome", "nome"],
            },
        ),
        migrations.CreateModel(
            name="RegistroMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "sintomas_observados",
                    models.TextField(
                        help_text="Descrição detalhada dos sintomas observados"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, help_text="Anotações adicionais sobre o diagnóstico"
                    ),
                ),
                (
                    "tratamento_aplicado",
                    models.TextField(blank=True, help_text="Tratamento aplicado"),
                ),
                (
                    "doenca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.doenca",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="core.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Médico",
                "verbose_name_plural": "Registros Médicos",
                "ordering": ["-data"],
            },
        ),
        migrations.AddField(
            model_name="doenca",
            name="sintomas",
            field=models.ManyToManyField(to="core.sintoma"),
        ),
    ]
