# Generated by Django 5.2 on 2025-04-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="sintomas_observados",
            field=models.ManyToManyField(blank=True, to="core.sintoma"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="idade",
            field=models.PositiveIntegerField(verbose_name="Idade"),
        ),
        migrations.CreateModel(
            name="Besta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("titulo", models.CharField(blank=True, max_length=200)),
                (
                    "nivel_ameaca",
                    models.CharField(
                        choices=[
                            ("01", "1/10"),
                            ("02", "2/10"),
                            ("03", "3/10"),
                            ("04", "4/10"),
                            ("05", "5/10"),
                            ("06", "6/10"),
                            ("07", "7/10"),
                            ("08", "8/10"),
                            ("09", "9/10"),
                            ("10", "10/10"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                ("aparencia", models.TextField()),
                ("habilidades", models.TextField()),
                ("anotacoes", models.TextField(blank=True)),
                (
                    "doenca_relacionada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bestas",
                        to="core.doenca",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_diagnostico", models.DateField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "doenca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.doenca"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
            ],
            options={
                "ordering": ["-data_diagnostico"],
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="doencas",
            field=models.ManyToManyField(
                related_name="pacientes", through="core.Diagnostico", to="core.doenca"
            ),
        ),
    ]
