# Generated by Django 5.2 on 2025-04-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_bunker_funcao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="sintomas_observados",
        ),
        migrations.RemoveField(
            model_name="doenca",
            name="sintomas",
        ),
        migrations.DeleteModel(
            name="Sintoma",
        ),
        migrations.AddField(
            model_name="doenca",
            name="sintomas",
            field=models.TextField(
                blank=True,
                help_text="Descreva os sintomas, separados por vírgula",
                verbose_name="Sintomas",
            ),
        ),
    ]
