# Generated by Django 5.2 on 2025-04-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_paciente_sintomas_observados_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="besta",
            name="doenca_relacionada",
        ),
        migrations.AddField(
            model_name="besta",
            name="doenca_relacionada",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="bestas", to="core.doenca"
            ),
        ),
    ]
