# Generated by Django 5.2 on 2025-04-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_besta_doenca_relacionada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="besta",
            name="doenca_relacionada",
            field=models.ManyToManyField(related_name="bestas", to="core.doenca"),
        ),
    ]
