# Generated by Django 5.2 on 2025-04-27 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_besta_doenca_relacionada"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="pergunta_secreta",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="usuario",
            name="resposta_secreta",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="AnotacaoPessoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
    ]
