# Generated by Django 5.2 on 2025-04-27 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_usuario_pergunta_secreta_usuario_resposta_secreta_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anotacaopessoal",
            options={
                "ordering": ["-data_atualizacao"],
                "verbose_name_plural": "Anotações Pessoais",
            },
        ),
        migrations.AddField(
            model_name="anotacaopessoal",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="anotacaopessoal",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Palavras-chave separadas por vírgula",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="anotacaopessoal",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anotacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
