# Generated by Django 5.2 on 2025-04-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_anotacaopessoal_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="pergunta_secreta",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="resposta_secreta",
        ),
    ]
