# Generated by Django 5.2 on 2025-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_usuario_pergunta_secreta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="pergunta_secreta",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="usuario",
            name="resposta_secreta",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
