# Generated by Django 5.2 on 2025-04-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usuario_pergunta_secreta_usuario_resposta_secreta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="pergunta_secreta",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="resposta_secreta",
        ),
    ]
