# Generated by Django 5.2 on 2025-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_usuario_pergunta_secreta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doenca",
            name="parte_afetada",
            field=models.CharField(
                choices=[
                    ("CAB", "Cabeça"),
                    ("OLH", "Olhos"),
                    ("OUV", "Ouvidos"),
                    ("NAR", "Nariz"),
                    ("BOC", "Boca"),
                    ("DEN", "Dentes"),
                    ("PES", "Pescoço"),
                    ("OMB", "Ombros"),
                    ("BRA", "Braços"),
                    ("COT", "Cotovelos"),
                    ("MAO", "Mãos"),
                    ("DED", "Dedos"),
                    ("TOR", "Tórax"),
                    ("COR", "Coração"),
                    ("PUL", "Pulmões"),
                    ("VAS", "Vasos sanguíneos"),
                    ("EST", "Estômago"),
                    ("FIG", "Fígado"),
                    ("BEX", "Bexiga"),
                    ("RIM", "Rins"),
                    ("INT", "Intestinos"),
                    ("ESP", "Esôfago"),
                    ("COL", "Coluna vertebral"),
                    ("OSS", "Ossos"),
                    ("MUS", "Músculos"),
                    ("JOE", "Joelhos"),
                    ("TOR", "Tornozelos"),
                    ("PES", "Pés"),
                    ("PEL", "Pele"),
                    ("MEN", "Mente"),
                ],
                max_length=3,
            ),
        ),
    ]
