# Generated by Django 5.2.8 on 2025-11-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_doenca_parte_afetada"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, unique=True, verbose_name="Nome"),
                ),
                (
                    "o_que_e",
                    models.TextField(
                        help_text="Descrição do ingrediente", verbose_name="O que é"
                    ),
                ),
                (
                    "o_que_faz",
                    models.TextField(
                        help_text="Propriedades e efeitos do ingrediente",
                        verbose_name="O que faz",
                    ),
                ),
                (
                    "contra_indicacoes",
                    models.TextField(
                        blank=True,
                        help_text="Situações em que não deve ser usado",
                        verbose_name="Contraindicações",
                    ),
                ),
                (
                    "reacoes_adversas",
                    models.TextField(
                        blank=True,
                        help_text="Possíveis efeitos colaterais",
                        verbose_name="Reações adversas",
                    ),
                ),
                (
                    "cuidados_ao_uso",
                    models.TextField(
                        blank=True,
                        help_text="Precauções necessárias",
                        verbose_name="Cuidados ao uso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "longevidade",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 80-100 anos",
                        max_length=200,
                        verbose_name="Longevidade",
                    ),
                ),
                (
                    "caracteristicas_fisicas",
                    models.TextField(
                        blank=True, verbose_name="Características físicas"
                    ),
                ),
                (
                    "cor_sangue",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cor do sangue"
                    ),
                ),
                (
                    "afinidade_magica",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Afinidade mágica"
                    ),
                ),
                (
                    "cuidados_especiais",
                    models.TextField(blank=True, verbose_name="Cuidados especiais"),
                ),
                (
                    "alimentacao",
                    models.TextField(blank=True, verbose_name="Alimentação"),
                ),
                (
                    "peculiaridades",
                    models.TextField(blank=True, verbose_name="Peculiaridades"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Raça",
                "verbose_name_plural": "Raças",
                "ordering": ["nome"],
            },
        ),
        migrations.RenameModel(
            old_name="Bunker",
            new_name="Cidade",
        ),
        migrations.AlterModelOptions(
            name="paciente",
            options={
                "ordering": ["cidade__nome", "nome"],
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.RenameField(
            model_name="paciente",
            old_name="bunker",
            new_name="cidade",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="bunker",
            new_name="cidade",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="tipo_sanguineo",
        ),
        migrations.AddField(
            model_name="paciente",
            name="afinidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fo", "Fogo"),
                    ("ra", "Raio"),
                    ("cu", "Cura"),
                    ("na", "Natureza"),
                    ("ag", "Água"),
                    ("ge", "Gelo"),
                    ("sa", "Sangue"),
                    ("ev", "Evocação"),
                    ("va", "Vazio"),
                    ("nn", "Nenhuma"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="doenca",
            name="parte_afetada",
            field=models.CharField(
                choices=[
                    ("CAB", "Cabeça"),
                    ("OLH", "Olhos"),
                    ("OUV", "Ouvidos"),
                    ("NAR", "Nariz"),
                    ("BOC", "Boca"),
                    ("DEN", "Dentes"),
                    ("PES", "Pescoço"),
                    ("OMB", "Ombros"),
                    ("BRA", "Braços"),
                    ("COT", "Cotovelos"),
                    ("MAO", "Mãos"),
                    ("DED", "Dedos"),
                    ("TOR", "Tórax"),
                    ("COR", "Coração"),
                    ("PUL", "Pulmões"),
                    ("VAS", "Vasos sanguíneos"),
                    ("EST", "Estômago"),
                    ("FIG", "Fígado"),
                    ("BEX", "Bexiga"),
                    ("RIM", "Rins"),
                    ("INT", "Intestinos"),
                    ("ESP", "Esôfago"),
                    ("COL", "Coluna vertebral"),
                    ("OSS", "Ossos"),
                    ("MUS", "Músculos"),
                    ("JOE", "Joelhos"),
                    ("TOR", "Tornozelos"),
                    ("PES", "Pés"),
                    ("PEL", "Pele"),
                    ("MEN", "Mente"),
                    ("CAN", "Canais de Essência"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="doenca",
            name="tipo",
            field=models.CharField(
                choices=[("F", "Física"), ("M", "Mental"), ("A", "Mágica")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="paciente",
            name="raca",
            field=models.ManyToManyField(related_name="racas", to="core.raca"),
        ),
        migrations.CreateModel(
            name="Remedio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição geral do remédio",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "modo_uso",
                    models.TextField(
                        blank=True,
                        help_text="Instruções de como usar",
                        verbose_name="Modo de uso",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "doencas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Doenças que este remédio trata",
                        related_name="remedios",
                        to="core.doenca",
                        verbose_name="Doenças",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remédio",
                "verbose_name_plural": "Remédios",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="diagnostico",
            name="remedios",
            field=models.ManyToManyField(
                blank=True,
                related_name="diagnosticos",
                to="core.remedio",
                verbose_name="Remédios prescritos",
            ),
        ),
        migrations.CreateModel(
            name="RemedioIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.CharField(
                        help_text="Ex: 2 colheres, 100g, 5 gotas",
                        max_length=200,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ingrediente",
                    ),
                ),
                (
                    "remedio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.remedio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente do Remédio",
                "verbose_name_plural": "Ingredientes do Remédio",
                "unique_together": {("remedio", "ingrediente")},
            },
        ),
        migrations.AddField(
            model_name="remedio",
            name="ingredientes",
            field=models.ManyToManyField(
                related_name="remedios",
                through="core.RemedioIngrediente",
                to="core.ingrediente",
            ),
        ),
    ]
