# Generated by Django 5.2.8 on 2025-11-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ingrediente_raca_rename_bunker_cidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postagem",
            name="autor",
        ),
        migrations.AddField(
            model_name="diagnostico",
            name="tratado",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.DeleteModel(
            name="Postagem",
        ),
    ]
