# Generated by Django 5.2.8 on 2025-11-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_postagem_autor_diagnostico_tratado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="besta",
            name="imagem",
        ),
        migrations.AddField(
            model_name="besta",
            name="contagio",
            field=models.TextField(
                blank=True, help_text="Descrição de como a besta pode contaminar outros"
            ),
        ),
        migrations.AddField(
            model_name="besta",
            name="corrompida_por_essencia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="besta",
            name="pode_contaminar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="besta",
            name="relacionada_com_essencia",
            field=models.BooleanField(default=False),
        ),
    ]
