# Generated by Django 5.2.8 on 2025-11-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_doenca_parte_afetada_alter_usuario_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="contatos_emergencia",
            field=models.TextField(
                blank=True,
                help_text="Nomes e informações de contato de emergência",
                verbose_name="Contatos de Emergência",
            ),
        ),
    ]
