# Generated by Django 5.2.8 on 2025-11-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_paciente_contatos_emergencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="raca",
            name="bpm",
            field=models.CharField(
                blank=True,
                help_text="Ex: 60-100 bpm",
                max_length=200,
                verbose_name="Batimentos por minuto",
            ),
        ),
        migrations.AddField(
            model_name="raca",
            name="pressao_arterial",
            field=models.CharField(
                blank=True,
                help_text="Ex: 120/80 mmHg",
                max_length=200,
                verbose_name="Pressão arterial",
            ),
        ),
    ]
