# Generated by Django 5.2.8 on 2025-11-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_raca_bpm_raca_pressao_arterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="fay_normal",
            field=models.CharField(
                blank=True,
                help_text="Tipo de Fay predominante ou natural do paciente",
                max_length=100,
                null=True,
                verbose_name="Fay Normal",
            ),
        ),
    ]
