# Generated by Django 5.2.1 on 2026-10-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_paciente_fay_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='parte_afetada',
            field=models.CharField(choices=[('CAB', 'Cabeça'), ('OLH', 'Olhos'), ('OUV', 'Ouvidos'), ('BRA', 'Braços'), ('MAO', 'Mãos'), ('DED', 'Dedos'), ('TOR', 'Tórax'), ('COR', 'Coração'), ('PUL', 'Pulmões'), ('VAS', 'Vasos sanguíneos'), ('EST', 'Estômago'), ('FIG', 'Fígado'), ('RIM', 'Rins'), ('INT', 'Intestinos'), ('COL', 'Coluna vertebral'), ('OSS', 'Ossos'), ('MUS', 'Músculos'), ('PEL', 'Pele'), ('MEN', 'Mente'), ('CAN', 'Canais de Essência'), ('SAN', 'Sangue'), ('OUT', 'Outros')], max_length=3),
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=200, verbose_name='Autor')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('conteudo', models.TextField(blank=True, help_text='Texto do livro (é nele que se fazem os comentários)', verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trecho', models.TextField(verbose_name='Trecho selecionado')),
                ('inicio', models.PositiveIntegerField(blank=True, null=True)),
                ('fim', models.PositiveIntegerField(blank=True, null=True)),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_livro', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.livro')),
            ],
            options={
                'verbose_name': 'Comentário de livro',
                'verbose_name_plural': 'Comentários de livros',
                'ordering': ['inicio', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MapaTeorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapa de teorização',
                'verbose_name_plural': 'Mapas de teorização',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='core.tema', verbose_name='Tema pai')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='core.tema', verbose_name='Tema'),
        ),
    ]
