# Generated by Django 5.2.1 on 2026-10-06 13:07

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0019_acervo_teorizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('arquivo', models.ImageField(upload_to=core.models.caminho_imagem, verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['data_envio', 'pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_imagem_content_7ac0bc_idx')],
            },
        ),
    ]
