# Generated by Django 5.2.1 on 2026-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mapa_compartilhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('MED', 'Médico'), ('ENG', 'Engenheiro'), ('FER', 'Ferreiro'), ('COZ', 'Cozinheiro'), ('ALQ', 'Alquimista'), ('BRU', 'Bruxo'), ('OUT', 'Outro'), ('ADM', 'Administrador')], default='OUT', max_length=3),
        ),
    ]
