# Generated by Django 5.2.1 on 2026-10-06 14:10

import unicodedata

from django.db import migrations, models


def preencher_ordenacao(apps, schema_editor):
    # Cópia da regra de core.models.chave_alfabetica (migrações não devem importar models)
    Livro = apps.get_model('core', 'Livro')
    for livro in Livro.objects.all():
        sem_acento = ''.join(c for c in unicodedata.normalize('NFKD', livro.titulo or '') if not unicodedata.combining(c))
        livro.titulo_ordenacao = sem_acento.casefold().strip()
        livro.save(update_fields=['titulo_ordenacao'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_usuario_profissoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo_ordenacao', 'titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='livro',
            name='titulo_ordenacao',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.RunPython(preencher_ordenacao, migrations.RunPython.noop),
    ]
