# Generated by Django 5.2.1 on 2026-10-06 14:13

import unicodedata

from django.db import migrations, models


def preencher_ordenacao(apps, schema_editor):
    # Cópia da regra de core.models.chave_alfabetica (migrações não devem importar models)
    Paciente = apps.get_model('core', 'Paciente')
    for paciente in Paciente.objects.all():
        sem_acento = ''.join(c for c in unicodedata.normalize('NFKD', paciente.nome or '') if not unicodedata.combining(c))
        paciente.nome_ordenacao = sem_acento.casefold().strip()
        paciente.save(update_fields=['nome_ordenacao'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_livro_ordem_alfabetica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['cidade__nome', 'nome_ordenacao', 'nome'], 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_ordenacao',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.RunPython(preencher_ordenacao, migrations.RunPython.noop),
    ]
